import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { generateGodotProject, createRuntimeEventReader, readRuntimeEvents, godotDiagnostics } from '../backends/godot4-dispatch.mjs';
import { buildProject, runProjectBuild } from '../adapters/node-project-build.mjs';
import { captureBuildSnapshot } from '../adapters/node-build-snapshot.mjs';

const golden = JSON.parse(await fs.readFile(new URL('./fixtures/scene-model/legacy-plan-v1.json', import.meta.url)));
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const first = '11111111-1111-4111-8111-111111111111';
const second = '22222222-2222-4222-8222-222222222222';
const sceneId = 'dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const actorId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const imageId = 'cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const godot = process.env.VIENTO_GODOT_BIN;
const example = fileURLToPath(new URL('../../examples/scene2d/', import.meta.url));
const scenePath = 'documents/scenes/demo.json';
const frame = value => `VIENTO_RUNTIME:${JSON.stringify(value)}\n`;
const plan = () => {
  const value = structuredClone(golden.plan);
  value.schemaVersion = 2;
  const base = value.actors[0];
  value.actors = [first, second].map((instanceId, index) => ({ ...structuredClone(base), instanceId,
    position: index ? [360, 100] : [100, 100], controls: index ? 'none' : 'arrows', speed: index ? 0 : 160,
    declaration: { ...base.declaration, propertyPath: `/actors/${index}` } }));
  return value;
};
const actorState = actor => ({ instanceId: actor.instanceId, objectId: actor.objectId, position: actor.position, state: 'idle' });
const lifecycle = value => ({ protocol: 2, event: 'ready', sceneObjectId: value.scene.objectId, actors: value.actors.map(actorState) });
const diagnostic = (actor, extra = {}) => ({ protocol: 2, event: 'diagnostic', severity: 'error', code: 'runtime_smoke_failed',
  message: '实例状态不一致', instanceId: actor.instanceId, objectId: actor.objectId, ...extra });

async function fixture(t) {
  const temporary = await fs.mkdtemp(path.join(os.tmpdir(), 'viento-instance-runtime-'));
  t.after(() => fs.rm(temporary, { recursive: true, force: true }));
  const root = path.join(temporary, 'workspace');
  await fs.cp(example, root, { recursive: true });
  const file = path.join(root, scenePath);
  const scene = JSON.parse(await fs.readFile(file));
  scene.schemaVersion = 2;
  const actor = scene.actors[0];
  scene.actors = [{ ...actor, instanceId: first }, { ...actor, instanceId: second, position: [420, 120], controls: 'none', speed: 0 }];
  await fs.writeFile(file, JSON.stringify(scene, null, 2) + '\n');
  return { root, temporary, scene };
}

async function inventory(root) {
  const values = {};
  for (const entry of await fs.readdir(root, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const file = path.join(entry.parentPath, entry.name);
    values[path.relative(root, file)] = hash(await fs.readFile(file));
  }
  return values;
}

test('instance backend dispatcher keeps legacy v1 fingerprint, generated bytes and source map intact', async () => {
  const generated = await generateGodotProject(golden.plan);
  assert.equal(generated.backend.sha256, 'dba885d7965715e56b1f1ac394dc78e3227d3502d23318a736dca6eb93beabe6');
  assert.equal(generated.backend.protocolVersion, 1);
  assert.equal(generated.backend.version, '0.1.0');
  assert.deepEqual(Object.fromEntries([...generated.files].map(([name, bytes]) => [name, hash(bytes)])), golden.godotFiles);
  assert.deepEqual(generated.sourceMap, golden.godotSourceMap);
  const ready = { protocol: 1, event: 'ready', sceneObjectId: golden.plan.scene.objectId,
    actors: golden.plan.actors.map(actor => ({ objectId: actor.objectId, position: actor.position, state: 'idle' })) };
  const runtime = readRuntimeEvents({ stdout: frame(ready) }, golden.plan);
  assert.deepEqual(runtime.events, [ready]); assert.deepEqual(runtime.diagnostics, []);
  assert.throws(() => generateGodotProject({ ...golden.plan, schemaVersion: 3 }), { errorCode: 'build_scene_version' });
});

test('instance generation gives repeated definitions stable distinct nodes and deduplicated resources', async () => {
  const value = plan(), before = structuredClone(value), generated = await generateGodotProject(value);
  assert.equal(generated.backend.protocolVersion, 2); assert.equal(generated.backend.version, '0.2.0');
  assert.notEqual(generated.backend.sha256, 'dba885d7965715e56b1f1ac394dc78e3227d3502d23318a736dca6eb93beabe6');
  const scene = JSON.parse(generated.files.get('scene.json'));
  assert.equal(scene.schemaVersion, 2);
  assert.deepEqual(scene.actors.map(actor => actor.instanceId), [first, second]);
  assert.equal(scene.actors[0].objectId, scene.actors[1].objectId);
  assert.equal(generated.imageFiles.size, 1);
  assert.equal(generated.sourceMap.schemaVersion, 2);
  assert.deepEqual(generated.sourceMap.objects.map(actor => actor.nodePath), [first, second].map(id => `/root/VientoScene/actor_${id.replaceAll('-', '_')}`));
  const reordered = await generateGodotProject({ ...value, actors: [...value.actors].reverse() });
  const byIdentity = output => Object.fromEntries(output.sourceMap.objects.map(actor => [actor.instanceId, actor.nodePath]));
  assert.deepEqual(byIdentity(reordered), byIdentity(generated));
  assert.deepEqual(value, before);
  assert.match(generated.files.get('runtime.gd').toString(), /set_meta\("viento_instance_id", actor\["instanceId"\]\)/);
});

test('instance protocol streams independently addressed state events and declaration diagnostics', () => {
  const value = plan(), observed = [], reader = createRuntimeEventReader(value, { onEvent: event => observed.push(event) });
  const ready = lifecycle(value), text = frame(ready);
  assert.deepEqual(reader.push(text.slice(0, 22)), []);
  assert.deepEqual(reader.push(text.slice(22)), [ready]);
  const moving = { protocol: 2, event: 'state', instanceId: first, objectId: value.actors[0].objectId, state: 'moving' };
  reader.push(frame(moving));
  reader.push(frame(diagnostic(value.actors[1])));
  const finished = { protocol: 2, event: 'finished', actors: value.actors.map(actorState).reverse(), fixedDelta: 0.25 };
  reader.push(frame(finished).trimEnd()); reader.finish(); reader.finish();
  assert.equal(observed.length, 4);
  assert.deepEqual(observed[1], moving);
  assert.equal(reader.diagnostics.length, 1);
  assert.equal(reader.diagnostics[0].instanceId, second);
  assert.equal(reader.diagnostics[0].relatedObjectId, value.actors[1].objectId);
  assert.equal(reader.diagnostics[0].objectId, value.scene.objectId);
  assert.equal(reader.diagnostics[0].sourcePath, value.scene.sourcePath);
  assert.equal(reader.diagnostics[0].propertyPath, '/actors/1');
});

test('instance protocol rejects missing, duplicate, mismatched, forged and legacy identities', () => {
  const value = plan(), ready = lifecycle(value), actor = value.actors[0];
  const invalid = frames => {
    const result = readRuntimeEvents({ stdout: frames.map(frame).join('') }, value);
    assert.ok(result.diagnostics.some(item => item.code === 'runtime_protocol_invalid'), JSON.stringify(frames));
  };
  for (const frames of [
    [{ ...ready, protocol: 1 }],
    [{ ...ready, actors: ready.actors.map(({ instanceId, ...item }) => item) }],
    [{ ...ready, actors: [ready.actors[0], ready.actors[0]] }],
    [{ ...ready, actors: [{ ...ready.actors[0], objectId: actorId }, ready.actors[1]] }],
    [ready, { protocol: 2, event: 'state', objectId: actor.objectId, state: 'moving' }],
    [ready, { protocol: 2, event: 'state', instanceId: first, objectId: actorId, state: 'moving' }],
    [ready, { protocol: 2, event: 'state', instanceId: 'unknown', objectId: actor.objectId, state: 'moving' }],
    [diagnostic(actor, { instanceId: undefined })],
    [diagnostic(actor, { objectId: actorId })],
    [diagnostic(actor, { sourcePath: '/outside' })],
    [diagnostic(actor, { resourceId: 'unknown' })],
    [diagnostic(actor, { instanceId: undefined, objectId: value.scene.objectId, resourceId: imageId })],
    [ready, ready],
    [{ protocol: 2, event: 'finished', actors: ready.actors, fixedDelta: 0.25 }],
    [ready, { protocol: 2, event: 'finished', actors: ready.actors, fixedDelta: 0.25 }, diagnostic(actor)],
  ]) invalid(frames);
  const changed = structuredClone(value); changed.actors[1].imageResourceId = null;
  assert.equal(readRuntimeEvents({ stdout: frame(diagnostic(changed.actors[1], { resourceId: imageId })) }, changed).diagnostics[0].code, 'runtime_protocol_invalid');
});

test('instance image failures resolve trusted field locations and report every affected instance', () => {
  const value = plan();
  value.actors.forEach((actor, index) => { actor.fieldSources.imageResourceId = { ...actor.declaration, propertyPath: `/actors/${index}/imageResourceId` }; });
  const result = readRuntimeEvents({ stdout: frame(diagnostic(value.actors[1], { code: 'runtime_image_failed', resourceId: imageId })) }, value);
  assert.equal(result.diagnostics[0].propertyPath, '/actors/1/imageResourceId');
  assert.equal(result.diagnostics[0].instanceId, second);
  const imported = godotDiagnostics({ status: 'failed', stdout: '', stderr: `ERROR: Cannot import ${imageId}` }, value);
  assert.deepEqual(imported.filter(item => item.code === 'godot_error').map(item => item.instanceId), [first, second]);
  assert.deepEqual(imported.filter(item => item.code === 'godot_error').map(item => item.propertyPath), ['/actors/0/imageResourceId', '/actors/1/imageResourceId']);
});

test('instance import diagnostics bound repeated shared-resource errors and oversized messages', () => {
  const value = plan(), base = value.actors[0];
  value.actors = Array.from({ length: 128 }, (_, index) => ({ ...structuredClone(base), instanceId: `instance-${index}`,
    declaration: { ...base.declaration, propertyPath: `/actors/${index}` } }));
  const line = `ERROR: Cannot import ${imageId} ${'x'.repeat(16000)}`;
  for (const status of ['succeeded', 'failed']) {
    const diagnostics = godotDiagnostics({ status, stdout: '', stderr: Array.from({ length: 100 }, () => line).join('\n') }, value);
    assert.equal(diagnostics.length, 256);
    assert.deepEqual(diagnostics.slice(0, 128).map(item => item.instanceId), value.actors.map(item => item.instanceId));
    assert.ok(diagnostics.every(item => item.message.length <= 4096));
    if (status === 'failed') assert.equal(diagnostics.at(-1).code, 'build_process_failed');
    else assert.equal(diagnostics.at(-1).code, 'godot_error');
  }
});

test('instance protocol bounds unfinished frames and event history', () => {
  const value = plan(), reader = createRuntimeEventReader(value);
  reader.push('VIENTO_RUNTIME:' + 'x'.repeat(64 * 1024)); reader.push('x'.repeat(64 * 1024));
  reader.push('\n' + frame(lifecycle(value)));
  assert.equal(reader.events.length, 1); assert.equal(reader.diagnostics.length, 1);
  for (let index = 0; index < 5000; index++) reader.push(frame({ protocol: 2, event: 'state', instanceId: first, objectId: value.actors[0].objectId, state: 'moving' }));
  assert.equal(reader.events.length, 4096); assert.equal(reader.diagnostics.length, 2);
});

test('instance snapshot freezes repeated definitions once and source diagnostics select the right instance', async t => {
  const { root } = await fixture(t), before = await inventory(root);
  const captured = await captureBuildSnapshot(root, sceneId);
  assert.equal(captured.ok, true, JSON.stringify(captured.diagnostics));
  assert.equal(captured.snapshot.schemaVersion, 1); assert.equal(captured.plan.schemaVersion, 2);
  assert.equal(captured.plan.actors.length, 2); assert.equal(captured.resources.size, 1);
  assert.equal(captured.plan.resources.length, 1);
  assert.deepEqual(captured.sourceLocations.actors.map(actor => actor.instanceId), [first, second]);
  assert.deepEqual(await inventory(root), before);
  const scene = JSON.parse(await fs.readFile(path.join(root, scenePath)));
  delete scene.actors[0].imageResourceId;
  await fs.writeFile(path.join(root, scenePath), JSON.stringify(scene));
  await fs.writeFile(path.join(root, 'assets/traveler.svg'), 'changed');
  const changed = await captureBuildSnapshot(root, sceneId);
  assert.equal(changed.ok, false);
  assert.equal(changed.diagnostics[0].propertyPath, '/actors/1/imageResourceId');
});

test('real Godot instances: shared definition and resource, independent movement, cold frozen run and protocol guard', {
  skip: !godot && 'Set VIENTO_GODOT_BIN to run real Godot instances', timeout: 120000,
}, async t => {
  const { root, temporary } = await fixture(t), before = await inventory(root), output = path.join(temporary, 'build');
  const built = await buildProject({ root, scene: sceneId, godot, output });
  assert.equal(built.ok, true, JSON.stringify(built));
  assert.equal(built.record.backend.protocolVersion, 2);
  assert.equal(built.record.artifact.files.filter(item => item.path.startsWith('images/')).length, 1);
  assert.deepEqual(await inventory(root), before);
  await fs.rename(root, `${root}-offline`);
  const run = await runProjectBuild({ buildDirectory: output, godot });
  assert.equal(run.ok, true, JSON.stringify(run));
  assert.deepEqual(run.record.events.filter(item => item.event === 'state').map(item => [item.instanceId, item.state]), [[first, 'moving'], [first, 'idle']]);
  const actors = run.record.events.find(item => item.event === 'finished').actors;
  assert.deepEqual(actors, [
    { instanceId: first, objectId: actorId, position: [240, 220], state: 'idle' },
    { instanceId: second, objectId: actorId, position: [420, 120], state: 'idle' },
  ]);
  assert.deepEqual(await inventory(`${root}-offline`), before);
  await assert.rejects(fs.stat(path.join(run.sessionDirectory, 'project')), { code: 'ENOENT' });
  const record = JSON.parse(await fs.readFile(path.join(output, 'build.json')));
  record.backend.protocolVersion = 1;
  await fs.writeFile(path.join(output, 'build.json'), JSON.stringify(record));
  const altered = await runProjectBuild({ buildDirectory: output, godot });
  assert.equal(altered.ok, false); assert.equal(altered.diagnostics[0].code, 'runtime_adapter_changed');
});
