import '../adapters/node-studio-core.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createHash } from 'node:crypto';
import { createSceneStructure, sceneStructureActors } from '../../engine/scene-structure.mjs';
import { resolveScene2DModel } from '../../engine/scene-model.mjs';
import { createScene2DPlan } from '../../engine/build-plan.mjs';
import { generateGodotProject } from '../backends/godot4-dispatch.mjs';
import { buildProject, runProjectBuild } from '../adapters/node-project-build.mjs';
import { captureBuildSnapshot } from '../adapters/node-build-snapshot.mjs';

const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const v1 = JSON.parse(await fs.readFile(new URL('./fixtures/scene-model/legacy-plan-v1.json', import.meta.url)));
const v2 = JSON.parse(await fs.readFile(new URL('./fixtures/scene-model/legacy-plan-v2.json', import.meta.url)));
const parent = '66666666-6666-4666-8666-666666666666', child = '77777777-7777-4777-8777-777777777777';
const groupScene = () => {
  const observed = structuredClone(v2.observed), source = observed.source.documents.find(item => item.record.id === v2.ids.scene);
  const value = JSON.parse(source.content.replace(/^\uFEFF/, '')); value.schemaVersion = 3;
  value.groups = [{ groupId: parent, name: 'Actors' }, { groupId: child, name: 'Child 🦊', parentGroupId: parent }];
  value.actors[0].groupId = child;
  source.content = '\uFEFF' + JSON.stringify(value, null, 2).replaceAll('\n', '\r\n'); source.sourceRevision = `sha256:${hash(source.content)}`;
  const result = resolveScene2DModel(observed, v2.ids.scene); assert.equal(result.ok, true, JSON.stringify(result.diagnostics));
  return { observed, source, value, model: result.model, plan: createScene2DPlan(observed, v2.ids.scene).plan };
};

test('groups leave frozen v1 and v2 plans, backend fingerprints, generated bytes and runtime source maps unchanged', async () => {
  for (const golden of [v1, v2]) {
    const created = createScene2DPlan(golden.observed, golden.ids.scene); assert.equal(created.ok, true);
    assert.deepEqual(created.plan, golden.plan);
    const generated = await generateGodotProject(created.plan);
    assert.deepEqual(Object.fromEntries([...generated.files].map(([name, bytes]) => [name, hash(bytes)])), golden.godotFiles);
    assert.deepEqual(generated.sourceMap, golden.godotSourceMap);
    assert.equal(generated.backend.sha256, golden === v1 ? 'dba885d7965715e56b1f1ac394dc78e3227d3502d23318a736dca6eb93beabe6' : golden.godotBackend.sha256);
  }
  for (const [name, expected] of Object.entries(v2.baselineSha256).filter(([name]) => name.startsWith('scripts/backends/'))) {
    assert.equal(hash(await fs.readFile(new URL(`../../${name}`, import.meta.url))), expected, name);
  }
});

test('schema3 compiles a flat v2 runtime plan and returns grouping only through the editor structure', async () => {
  const { model, plan, observed } = groupScene(), before = structuredClone(observed), structure = createSceneStructure(model);
  assert.equal(model.schemaVersion, 3); assert.equal(plan.schemaVersion, 2);
  assert.deepEqual(plan.actors, v2.plan.actors); assert.deepEqual(plan.resources, v2.plan.resources);
  assert.deepEqual(plan.requiredCapabilities, v2.plan.requiredCapabilities); assert.equal(plan.groups, undefined); assert.equal(plan.sceneStructure, undefined);
  assert.deepEqual(structure, { format: 'viento-scene-structure', schemaVersion: 1, sourceSchemaVersion: 3,
    groups: model.groups, memberships: [{ instanceId: v2.ids.instances[0], groupId: child }] });
  const enriched = sceneStructureActors(structure, plan.actors); assert.deepEqual(enriched, model.actors);
  assert.deepEqual(enriched.map(actor => actor.instanceId), v2.ids.instances); assert.equal(enriched[1].groupId, undefined);
  const generated = await generateGodotProject(plan); assert.equal(generated.backend.sha256, v2.godotBackend.sha256);
  const runtime = JSON.parse(generated.files.get('scene.json')); assert.equal(runtime.schemaVersion, 2);
  assert.equal(runtime.groups, undefined); assert.ok(runtime.actors.every(actor => !Object.hasOwn(actor, 'groupId')));
  assert.equal(JSON.stringify(generated.sourceMap).includes(parent), false); assert.deepEqual(observed, before);
  enriched[0].position[0] = 999; structure.groups[0].name = 'Only caller'; assert.equal(model.groups[0].name, 'Actors'); assert.notEqual(model.actors[0].position[0], 999);
});

test('structure helpers retain old flat callers and reject malformed versions, references, collisions and metadata', () => {
  assert.equal(createSceneStructure({ schemaVersion: 1 }), undefined); assert.equal(createSceneStructure({ schemaVersion: 2 }), undefined);
  const flat = sceneStructureActors(undefined, v2.plan.actors); assert.deepEqual(flat, v2.plan.actors); flat[0].position[0] = 999; assert.notEqual(v2.plan.actors[0].position[0], 999);
  const { model, plan } = groupScene(), structure = createSceneStructure(model);
  for (const mutate of [value => { value.schemaVersion = 2; }, value => { value.sourceSchemaVersion = 2; },
    value => { value.hostPath = '/private/project'; }, value => { value.groups[0].transform = [100, 100]; },
    value => { value.groups[0].parentGroupId = child; }, value => { value.groups[0].groupId = v2.ids.instances[0]; },
    value => { value.memberships.push({ ...value.memberships[0] }); }, value => { value.memberships[0].instanceId = parent; },
    value => { value.memberships[0].groupId = v2.ids.instances[1]; }, value => { value.memberships[0].unknown = true; },
    value => { value.groups[0].parentGroupId = null; }, value => { delete value.groups; }]) {
    const changed = structuredClone(structure); mutate(changed);
    assert.throws(() => sceneStructureActors(changed, plan.actors), { errorCode: 'scene_structure_invalid' });
  }
  for (const actors of [[...plan.actors, plan.actors[0]], [{ ...plan.actors[0], instanceId: null }], [{ ...plan.actors[0], objectId: null }], [{ ...plan.actors[0], groupId: parent }]]) {
    assert.throws(() => sceneStructureActors(structure, actors), { errorCode: 'scene_structure_invalid' });
  }
});

test('group membership and name changes affect editor structure and source revision without changing actor runtime behavior', () => {
  const first = groupScene(), next = structuredClone(first.observed), source = next.source.documents.find(item => item.record.id === v2.ids.scene);
  const value = JSON.parse(source.content.replace(/^\uFEFF/, '')); value.groups[1].name = 'Changed'; value.actors[0].groupId = parent;
  source.content = JSON.stringify(value); source.sourceRevision = `sha256:${hash(source.content)}`;
  const result = resolveScene2DModel(next, v2.ids.scene), plan = createScene2DPlan(next, v2.ids.scene).plan;
  assert.equal(result.ok, true); assert.deepEqual(plan.actors, first.plan.actors); assert.deepEqual(plan.resources, first.plan.resources);
  assert.notEqual(plan.scene.sourceRevision, first.plan.scene.sourceRevision); assert.notDeepEqual(createSceneStructure(result.model), createSceneStructure(first.model));
});

async function inventory(root) {
  const result = {};
  for (const item of await fs.readdir(root, { recursive: true, withFileTypes: true })) if (item.isFile()) {
    const file = path.join(item.parentPath, item.name); result[path.relative(root, file)] = hash(await fs.readFile(file));
  }
  return result;
}
const godot = process.env.VIENTO_GODOT_BIN;
test('real Godot runs a frozen schema3 source through unchanged runtime2 after the author workspace goes offline', {
  skip: !godot && 'Set VIENTO_GODOT_BIN to run the real grouped-scene build', timeout: 120000,
}, async t => {
  const temporary = await fs.mkdtemp(path.join(os.tmpdir(), 'viento-group-runtime-')); t.after(() => fs.rm(temporary, { recursive: true, force: true }));
  const root = path.join(temporary, 'workspace'), output = path.join(temporary, 'build'); await fs.cp(new URL('../../examples/scene2d/', import.meta.url), root, { recursive: true });
  const file = path.join(root, 'documents/scenes/demo.json'), value = JSON.parse(await fs.readFile(file));
  const actor = value.actors[0]; value.schemaVersion = 3; value.groups = [{ groupId: parent, name: 'Characters' }, { groupId: child, name: 'Nested', parentGroupId: parent }];
  value.actors = [{ ...actor, instanceId: v2.ids.instances[0], groupId: child }, { ...actor, instanceId: v2.ids.instances[1], groupId: parent, position: [420, 120], controls: 'none', speed: 0 }];
  await fs.writeFile(file, JSON.stringify(value, null, 2) + '\n'); const before = await inventory(root), captured = await captureBuildSnapshot(root, v2.ids.scene);
  assert.equal(captured.ok, true, JSON.stringify(captured.diagnostics)); assert.equal(captured.plan.schemaVersion, 2); assert.equal(captured.sceneStructure.groups.length, 2);
  const built = await buildProject({ root, scene: v2.ids.scene, godot, output }); assert.equal(built.ok, true, JSON.stringify(built));
  assert.equal(built.record.backend.sha256, v2.godotBackend.sha256); assert.deepEqual(await inventory(root), before);
  const frozen = JSON.parse(await fs.readFile(path.join(output, 'snapshot.json'))); assert.equal(frozen.plan.schemaVersion, 2); assert.equal(frozen.sceneStructure, undefined);
  assert.equal(JSON.parse(frozen.source.documents.find(item => item.record.id === v2.ids.scene).content).schemaVersion, 3);
  await fs.rename(root, root + '-offline'); const run = await runProjectBuild({ buildDirectory: output, godot }); assert.equal(run.ok, true, JSON.stringify(run));
  assert.deepEqual(run.record.events.find(item => item.event === 'finished').actors, [
    { instanceId: v2.ids.instances[0], objectId: actor.objectId, position: [240, 220], state: 'idle' },
    { instanceId: v2.ids.instances[1], objectId: actor.objectId, position: [420, 120], state: 'idle' },
  ]); assert.deepEqual(await inventory(root + '-offline'), before);
});
