import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { resolveScene2DModel } from '../../engine/scene-model.mjs';
import { createScene2DPlan, scene2DModelToPlan, validateScene2DRegistration } from '../../engine/build-plan.mjs';
import { canonicalJson } from '../../engine/world-projection.mjs';
import { generateGodotProject } from '../backends/godot4.mjs';

// Frozen using the actual planner before extraction, never generated by the
// implementation under test. Includes exact build DTO, snapshot and artifacts.
const golden = JSON.parse(await fs.readFile(new URL('./fixtures/scene-model/legacy-plan-v1.json', import.meta.url), 'utf8'));
const { ids } = golden;
const hash = text => createHash('sha256').update(text).digest('hex');
const fixture = () => structuredClone(golden.observed);
const document = (observed, id = ids.scene) => observed.source.documents.find(item => item.record.id === id);
const parse = text => JSON.parse(text.replace(/^\uFEFF/, ''));
const serialize = value => '\uFEFF' + JSON.stringify(value, null, '\t').replaceAll('\n', '\r\n') + '\r\n \t';
const setText = (observed, id, text) => {
  const source = document(observed, id);
  source.content = text; source.sourceRevision = `sha256:${hash(text)}`;
  return source;
};
const change = (observed, id, mutate) => {
  const value = parse(document(observed, id).content); mutate(value);
  return setText(observed, id, serialize(value));
};
const resolved = (observed, options) => {
  const result = resolveScene2DModel(observed, ids.scene, options);
  assert.equal(result.ok, true, JSON.stringify(result.diagnostics));
  assert.deepEqual(result.diagnostics, []);
  return result.model;
};
const actorSource = (model, id) => model.sourceLocations.actors.find(actor => actor.objectId === id);
function span(location, observed, { id = location.objectId, pointer = location.propertyPath, anchor = pointer, exact = true, raw } = {}) {
  const source = document(observed, id);
  assert.equal(location.objectId, id);
  assert.equal(location.sourcePath, source.sourcePath);
  assert.equal(location.propertyPath, pointer);
  assert.equal(location.sourceRevision, source.sourceRevision);
  const range = location.sourceRange;
  assert.ok(range, JSON.stringify(location));
  assert.equal(range.encoding, 'utf-16');
  assert.equal(range.propertyPath, anchor);
  assert.equal(range.exact, exact);
  assert.ok(Number.isInteger(range.start) && Number.isInteger(range.end));
  assert.ok(range.start >= 0 && range.end > range.start && range.end <= source.content.length);
  const text = source.content.slice(range.start, range.end);
  if (raw !== undefined) assert.equal(text, raw);
  return text;
}
function noSourceText(value) {
  assert.ok(!JSON.stringify(value).includes('PRIVATE_AUTHOR_BODY_ONLY_IN_DOCUMENT'));
  const visit = item => {
    if (!item || typeof item !== 'object') return;
    for (const [key, child] of Object.entries(item)) {
      assert.ok(!['content', 'sourceText', 'rawContent', 'cst', 'tokens'].includes(key), `Unexpected source text container: ${key}`);
      visit(child);
    }
  };
  visit(value);
}
function explicitCoreActor(observed) {
  change(observed, ids.scene, value => {
    value.actors[0] = { objectId: ids.core, position: [100.25, 200], size: [80, 60], color: '#ffffff', speed: 160, controls: 'arrows' };
  });
  observed.projection.relations.push({ sourceObjectId: ids.scene, targetObjectId: ids.core });
  document(observed).record.relations.push({ kind: 'references', targetId: ids.core });
}

test('scene model preserves frozen legacy plan, build snapshot and generated Godot files exactly', async () => {
  const observed = fixture(), before = structuredClone(observed), model = resolved(observed);
  assert.equal(golden.baselinePlannerSha256, '41a6bbfa8107623dec967ac0b4493107f46c1590c7b151ccf807feddbc945716');
  assert.equal(model.format, 'viento-scene-model');
  assert.equal(model.schemaVersion, 1);
  assert.equal(model.projectId, golden.plan.projectId);
  assert.equal(model.worldId, golden.plan.worldId);
  assert.equal(model.worldRevision, golden.plan.worldRevision);
  assert.equal(Object.hasOwn(model, 'requiredCapabilities'), false);
  const plan = scene2DModelToPlan(model);
  assert.deepEqual(plan, golden.plan);
  assert.deepEqual(createScene2DPlan(observed, ids.scene), { ok: true, plan: golden.plan, diagnostics: [] });
  assert.deepEqual(createScene2DPlan(observed, document(observed).sourcePath).plan, golden.plan);
  const snapshot = { format: 'viento-build-snapshot', schemaVersion: 1, source: observed.source, plan };
  assert.equal(`sha256:${hash(canonicalJson(snapshot))}`, golden.snapshotId);
  const generated = await generateGodotProject(plan);
  assert.deepEqual(Object.fromEntries([...generated.files].map(([name, text]) => [name, hash(text)])), golden.godotFiles);
  assert.deepEqual(generated.sourceMap, golden.godotSourceMap);
  assert.equal(Object.hasOwn(plan, 'sourceLocations'), false);
  noSourceText(model);
  assert.deepEqual(observed, before);
});

test('source locations retain exact BOM, CRLF, Unicode and escaped JSON token offsets', () => {
  const observed = fixture(), model = resolved(observed), scene = document(observed);
  assert.ok(scene.content.startsWith('\uFEFF{\r\n'));
  const root = span(model.sourceLocations.scene, observed, { pointer: '' });
  assert.equal(model.sourceLocations.scene.sourceRange.start, 1);
  assert.equal(model.sourceLocations.scene.sourceRange.end, scene.content.lastIndexOf('}') + 1);
  assert.deepEqual(JSON.parse(root), parse(scene.content));
  const first = actorSource(model, ids.first);
  span(first.definition, observed, { id: ids.first, pointer: '' });
  assert.deepEqual(JSON.parse(span(first.declaration, observed, { id: ids.scene, pointer: '/actors/0' })), parse(scene.content).actors[0]);
  const rawPosition = '[\r\n\t\t\t\t100.25,\r\n\t\t\t\t200\r\n\t\t\t]';
  span(first.fields.position, observed, { id: ids.scene, pointer: '/actors/0/position', raw: rawPosition });
  assert.equal(first.fields.position.sourceRange.start, scene.content.indexOf(rawPosition));
  // A UTF-8 byte offset or code-point offset would disagree after 中文🦊.
  assert.notEqual(first.fields.position.sourceRange.start, Buffer.byteLength(scene.content.slice(0, first.fields.position.sourceRange.start)));
  assert.notEqual(first.fields.position.sourceRange.start, [...scene.content.slice(0, first.fields.position.sourceRange.start)].length);
  span(first.fields.speed, observed, { id: ids.first, pointer: '/configuration/speed', raw: '1.6e2' });
  assert.equal(first.fields.speed.sourceRange.start, document(observed, ids.first).content.indexOf('1.6e2'));
  assert.equal(model.scene.title, '中文🦊 场景');
  assert.equal(model.actors[0].speed, 160);
});

test('inherited dimensions have independent precise sources and an honest composite size anchor', () => {
  const observed = fixture(), model = resolved(observed), first = actorSource(model, ids.first), second = actorSource(model, ids.second);
  assert.deepEqual(model.actors[0].size, [80, 60]);
  span(first.fields['size/0'], observed, { id: ids.first, pointer: '/configuration/width', raw: '80' });
  span(first.fields['size/1'], observed, { id: ids.first, pointer: '/configuration/height', raw: '60' });
  assert.deepEqual(JSON.parse(span(first.fields.size, observed, { id: ids.first, pointer: '/configuration', exact: false })), parse(document(observed, ids.first).content).configuration);
  assert.equal(scene2DModelToPlan(model).actors[0].fieldSources.size.propertyPath, '/configuration/width');
  span(first.fields.imageResourceId, observed, { id: ids.first, pointer: '/configuration/image', raw: JSON.stringify(ids.image) });
  span(second.fields['size/0'], observed, { id: ids.scene, pointer: '/actors/1/size/0', raw: '30' });
  span(second.fields['size/1'], observed, { id: ids.scene, pointer: '/actors/1/size/1', raw: '45' });
  span(second.fields.imageResourceId, observed, { id: ids.scene, pointer: '/actors/1/imageResourceId', raw: 'null' });
  assert.equal(Object.hasOwn(model.actors[1], 'imageResourceId'), false);
  assert.deepEqual(model.actors.map(actor => actor.origin), [0, 1].map(() => ({ objectId: ids.core,
    sourcePath: document(observed, ids.core).sourcePath, sourceRevision: document(observed, ids.core).sourceRevision })));
});

test('explicit null, missing image and disabled projection defaults retain distinct semantics and sources', () => {
  const observed = fixture();
  change(observed, ids.scene, value => { delete value.actors[1].imageResourceId; });
  let model = resolved(observed);
  assert.equal(model.actors[1].imageResourceId, ids.image);
  span(actorSource(model, ids.second).fields.imageResourceId, observed, { id: ids.second, pointer: '/configuration/image', raw: JSON.stringify(ids.image) });
  change(observed, ids.scene, value => { value.actors[1].useProjectionDefaults = false; });
  model = resolved(observed);
  assert.equal(Object.hasOwn(model.actors[1], 'imageResourceId'), false);
  assert.equal(model.actors[1].speed, 17);
  span(actorSource(model, ids.second).fields.speed, observed, { id: ids.scene, pointer: '/actors/1/speed', raw: '17' });
  span(actorSource(model, ids.second).fields.imageResourceId, observed, {
    id: ids.scene, pointer: '/actors/1/imageResourceId', anchor: '/actors/1', exact: false,
  });
});

test('unknown fields use decoded JSON Pointer keys and exact value ranges', () => {
  const observed = fixture();
  change(observed, ids.scene, value => { value.actors[0]['notes/~🦊'] = '未知中文 🦊'; });
  // Both slash/tilde and the surrogate pair are escaped in the original key.
  const source = document(observed);
  setText(observed, ids.scene, source.content.replace('"notes/~🦊"', '"notes\\u002f\\u007e\\ud83e\\udd8a"'));
  const before = structuredClone(observed), result = resolveScene2DModel(observed, ids.scene);
  assert.equal(result.ok, false);
  assert.equal(result.model, null);
  assert.equal(result.diagnostics.length, 1);
  const diagnostic = result.diagnostics[0];
  assert.equal(diagnostic.code, 'build_feature_unsupported');
  span(diagnostic, observed, { id: ids.scene, pointer: '/actors/0/notes~1~0🦊', raw: '"未知中文 🦊"' });
  assert.deepEqual(observed, before);
});

test('missing scene and actor fields locate the nearest existing container without claiming exactness', () => {
  const observed = fixture();
  explicitCoreActor(observed);
  change(observed, ids.scene, value => { delete value.background; delete value.actors[0].speed; });
  const result = resolveScene2DModel(observed, ids.scene);
  assert.equal(result.ok, false);
  assert.equal(result.model, null);
  const background = result.diagnostics.find(item => item.propertyPath === '/background');
  const speed = result.diagnostics.find(item => item.propertyPath === '/actors/0/speed');
  assert.equal(background.code, 'build_scene_value');
  assert.equal(speed.code, 'build_actor_value');
  assert.deepEqual(JSON.parse(span(background, observed, { pointer: '/background', anchor: '', exact: false })), parse(document(observed).content));
  assert.deepEqual(JSON.parse(span(speed, observed, { pointer: '/actors/0/speed', anchor: '/actors/0', exact: false })), parse(document(observed).content).actors[0]);
});

test('invalid inherited values locate projection configuration while scene overrides locate declarations', () => {
  const observed = fixture();
  change(observed, ids.first, value => { value.configuration.height = 4096; });
  change(observed, ids.scene, value => { value.actors[1].speed = -1; });
  const result = resolveScene2DModel(observed, ids.scene);
  assert.equal(result.ok, false);
  const height = result.diagnostics.find(item => item.propertyPath === '/configuration/height');
  const speed = result.diagnostics.find(item => item.propertyPath === '/actors/1/speed');
  assert.equal(height.code, 'build_projection_invalid');
  assert.equal(speed.code, 'build_actor_value');
  span(height, observed, { id: ids.first, pointer: '/configuration/height', raw: '4096' });
  span(speed, observed, { id: ids.scene, pointer: '/actors/1/speed', raw: '-1' });
});

test('actor reordering retains identity and definition but updates declaration pointers and revision', () => {
  const observed = fixture(), original = resolved(observed), originalCopy = structuredClone(original);
  change(observed, ids.scene, value => { value.actors.reverse(); });
  const before = structuredClone(observed), reordered = resolved(observed);
  assert.deepEqual(reordered.actors.map(item => item.objectId), [ids.second, ids.first]);
  for (const [index, id] of [ids.second, ids.first].entries()) {
    const previous = actorSource(original, id), current = actorSource(reordered, id);
    assert.deepEqual(current.definition, previous.definition);
    assert.notEqual(current.declaration.sourceRevision, previous.declaration.sourceRevision);
    assert.equal(JSON.parse(span(current.declaration, observed, { id: ids.scene, pointer: `/actors/${index}` })).objectId, id);
    span(current.fields.position, observed, { id: ids.scene, pointer: `/actors/${index}/position` });
  }
  assert.deepEqual(original, originalCopy);
  assert.deepEqual(observed, before);
});

test('non-JSON actor definitions retain identity and revision without leaking body text or fabricated ranges', () => {
  const observed = fixture(); explicitCoreActor(observed);
  const before = structuredClone(observed), model = resolved(observed), source = actorSource(model, ids.core);
  assert.deepEqual(source.definition, { objectId: ids.core, sourcePath: 'documents/oc.md', propertyPath: '',
    sourceRevision: document(observed, ids.core).sourceRevision });
  span(source.declaration, observed, { id: ids.scene, pointer: '/actors/0' });
  span(source.fields.speed, observed, { id: ids.scene, pointer: '/actors/0/speed', raw: '160' });
  assert.equal(Object.hasOwn(model.actors[0], 'origin'), false);
  noSourceText(model);
  assert.deepEqual(observed, before);
});

test('runtime rejects duplicate decoded root and actor keys while registration preserves legacy last-key semantics', () => {
  for (const duplicate of [
    { add: text => text.replace('"ti\\u0074le":', '"title": "discarded",\r\n\t"ti\\u0074le":'), pointer: '/title' },
    { add: text => text.replace('"position":', '"position": [999,999],\r\n\t\t\t"posi\\u0074ion":'), pointer: '/actors/0/position' },
  ]) {
    const observed = fixture();
    setText(observed, ids.scene, duplicate.add(document(observed).content));
    const before = structuredClone(observed), runtime = resolveScene2DModel(observed, ids.scene);
    assert.equal(runtime.ok, false);
    assert.equal(runtime.model, null);
    assert.ok(runtime.diagnostics.some(item => item.code === 'build_scene_json' && item.propertyPath === duplicate.pointer));
    const registration = resolved(observed, { mode: 'registration' });
    assert.equal(registration.scene.title, '中文🦊 场景');
    assert.deepEqual(registration.actors[0].position, [100.25, 200]);
    assert.equal(validateScene2DRegistration(observed, ids.scene).ok, true);
    const visit = value => {
      if (!value || typeof value !== 'object') return;
      if (value.sourcePath === document(observed).sourcePath) assert.equal(Object.hasOwn(value, 'sourceRange'), false);
      for (const child of Object.values(value)) visit(child);
    };
    visit(registration.sourceLocations);
    assert.deepEqual(observed, before);
  }
});

test('registration recovers legacy duplicate fields whose discarded value exceeds source-index budgets', () => {
  for (const hidden of ['['.repeat(66) + '0' + ']'.repeat(66), '[' + Array(100001).fill('0').join(',') + ']']) {
    const observed = fixture();
    setText(observed, ids.scene, document(observed).content.replace('"ti\\u0074le":', `"title": ${hidden},\r\n\t"ti\\u0074le":`));
    const before = structuredClone(observed);
    // The old JSON.parse planner accepted this last-key value; its effective
    // declaration is exactly the frozen legacy fixture despite the hidden tree.
    assert.deepEqual(parse(document(observed).content), parse(document(golden.observed).content));
    const runtime = resolveScene2DModel(observed, ids.scene);
    assert.equal(runtime.ok, false);
    assert.equal(runtime.model, null);
    assert.ok(runtime.diagnostics.some(item => item.code === 'build_scene_json'));
    const model = resolved(observed, { mode: 'registration' });
    assert.equal(model.scene.title, golden.plan.scene.title);
    assert.deepEqual(model.actors.map(actor => actor.position), golden.plan.actors.map(actor => actor.position));
    assert.equal(validateScene2DRegistration(observed, ids.scene).ok, true);
    const visit = value => {
      if (!value || typeof value !== 'object') return;
      assert.equal(Object.hasOwn(value, 'sourceRange'), false);
      for (const child of Object.values(value)) visit(child);
    };
    visit(model.sourceLocations);
    assert.deepEqual(observed, before);
    setText(observed, ids.scene, document(observed).content.replace(hidden, hidden.slice(1)));
    const malformed = resolveScene2DModel(observed, ids.scene, { mode: 'registration' });
    assert.equal(malformed.ok, false);
    assert.equal(malformed.model, null);
    assert.ok(malformed.diagnostics.some(item => item.code === 'build_scene_json'));
  }
});

test('registration recovery does not depend on current projection JSON, revision or resolved defaults', () => {
  for (const text of ['', '{ broken projection', '{"configuration":{"speed":10,"spe\\u0065d":20}}']) {
    const observed = fixture();
    for (const id of [ids.first, ids.second]) {
      document(observed, id).content = text;
      document(observed, id).sourceRevision = null;
    }
    const before = structuredClone(observed), model = resolved(observed, { mode: 'registration' });
    assert.deepEqual(model.actors[0].position, [100.25, 200]);
    assert.equal(Object.hasOwn(model.actors[0], 'size'), false);
    assert.equal(actorSource(model, ids.first).definition.sourceRevision, null);
    assert.equal(resolveScene2DModel(observed, ids.scene).ok, false);
    assert.deepEqual(observed, before);
  }
});

test('registration recovery does not derive locations from even valid current projection bodies', () => {
  const observed = fixture(), model = resolved(observed, { mode: 'registration' });
  for (const id of [ids.first, ids.second]) {
    const location = actorSource(model, id).definition;
    assert.equal(location.sourceRevision, document(observed, id).sourceRevision);
    assert.equal(Object.hasOwn(location, 'sourceRange'), false);
  }
  // A registration-only observation can supply opaque bodies: the availability
  // check is allowed, but no repeated access for parsing or source indexing.
  const counts = new Map();
  for (const id of [ids.first, ids.second]) Object.defineProperty(document(observed, id), 'content', { get() {
    const reads = (counts.get(id) || 0) + 1; counts.set(id, reads);
    assert.equal(reads, 1, 'Recovery must not inspect current projection text');
    return '{ unavailable current projection';
  } });
  assert.equal(resolveScene2DModel(observed, ids.scene, { mode: 'registration' }).ok, true);
  assert.deepEqual([...counts.values()], [1, 1]);
});

test('registration recovery still rejects missing explicit position and broken scene-to-actor registrations', () => {
  const observed = fixture();
  change(observed, ids.scene, value => { delete value.actors[0].position; });
  observed.projection.relations = observed.projection.relations.filter(item => !(item.sourceObjectId === ids.scene && item.targetObjectId === ids.first));
  const result = resolveScene2DModel(observed, ids.scene, { mode: 'registration' });
  assert.equal(result.ok, false);
  assert.ok(result.diagnostics.some(item => item.code === 'build_actor_unlinked'));
  const position = result.diagnostics.find(item => item.code === 'build_actor_value' && item.propertyPath === '/actors/0/position');
  span(position, observed, { pointer: '/actors/0/position', anchor: '/actors/0', exact: false });
});

test('re-resolving changed source recalculates UTF-16 ranges and leaves old model and build DTO independent', () => {
  const observed = fixture(), before = resolved(observed), beforeCopy = structuredClone(before);
  const oldRange = actorSource(before, ids.first).fields.position.sourceRange;
  setText(observed, ids.scene, document(observed).content.replace('中文🦊 场景', '额外中文🦊🦊 中文🦊 场景'));
  const after = resolved(observed), current = actorSource(after, ids.first).fields.position;
  assert.notEqual(current.sourceRevision, actorSource(before, ids.first).fields.position.sourceRevision);
  assert.ok(current.sourceRange.start > oldRange.start);
  span(current, observed, { pointer: '/actors/0/position', raw: span(actorSource(before, ids.first).fields.position, golden.observed) });
  assert.deepEqual(before, beforeCopy);
  const plan = scene2DModelToPlan(after), afterCopy = structuredClone(after);
  plan.actors[0].position[0] = 999;
  plan.scene.viewport[0] = 999;
  plan.actors[0].fieldSources.speed.propertyPath = '/changed';
  assert.deepEqual(after, afterCopy);
});
